Output spring-boot.gif

Require echo

Set Shell "bash"
Set FontSize 24
Set Width 1600
Set Height 600

Type "progen" Sleep 1s Enter

#Sleep 1s  Enter@1s
Sleep 1s  Type "myapp" Sleep 1s  Enter
Sleep 1s  Type "com.sivalabs" Sleep 1s  Enter
Sleep 1s  Type "myapp" Sleep 1s  Enter
Sleep 1s  Type "1.0.0" Sleep 1s  Enter
Sleep 1s  Type "com.sivalabs.myapp" Sleep 1s  Enter
Enter@2s
Enter@2s
Enter@2s

Sleep 2s
